### PR TITLE
feat: add drizzle and neon serverless

### PR DESCRIPTION
**Pull request by desujoy**
- check `@/lib/db/schema.ts` to see the database schema
- check `@/lib/db/helper.ts` to see some helper function examples

### CODE REVIEW

**Review by shreyvarshney1 — APPROVED** [review]

**Comment by desujoy** [comment]
```ts
console.log(JSON.stringify(await getProductById(4, "Fertilizer")));
```
Output:
```json
{"productId":4,"name":"Diammonium Phosphate (DAP)","description":"Balanced nitrogen and phosphorus fertilizer great for seed germination and early plant growth.","category":"Fertilizers","price":"0.45","stock":100,"imageUrl":"/img/dap.jpg","createdAt":"2024-12-13T06:32:42.403Z","fertilizerId":16,"type":"Organic","nutrientContent":"","recommendedCrops":""}
```

**Comment by shreyvarshney1** [comment]
> Output:
> 
> ```json
> {"category":"Fertilizers","fertilizerId":16}
> ```

@desujoy this will create confusion and problem for other category products. Try to change ```fertilizerId``` to ```productID```

**Comment by desujoy** [comment]
> > Output:
> > ```json
> > {"category":"Fertilizers","fertilizerId":16}
> > ```
> 
> @desujoy this will create confusion and problem for other category products. Try to change `fertilizerId` to `productID`

fertilizerId and productId are primary keys for different tables

**Review by shreyvarshney1 — CHANGES_REQUESTED** [review]
Check if above-mentioned changes are necessary or required then make the aforementioned adjustments

**Review by shreyvarshney1 — APPROVED** [review]

**Comment by desujoy** [comment]
@shreyvarshney1 add comment in the line you want me to change

**Comment by shreyvarshney1** [comment]
> @shreyvarshney1 add comment in the line you want me to change

resolved - i inferred schema then i figured.

**Review by AyushPandey003 — APPROVED** [review]

**Pull request merged**
